FROM cypress/included:10.6.0

ARG UNAME=testuser
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME

# install docker
# we can make this unnecessary with a db reset API endpoint instead
#
# docker-compose will do bind mount to docker.sock which is dangerous!
RUN apt update -y
RUN apt install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

#doing "focal" instead of $(lsb_release -cs) because "bullseye" (this image) not available yet
RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  focal stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt update -y
RUN apt install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y

USER $UNAME